services:
  sito_base:
    image: nginx
    volumes:
     - Volume1:/etc/nginx/templates
    ports:
      - "8080:80"
    container_name: sito_base

  site1:
    build:
      context: ./sito1
      dockerfile: Dockerfile
    container_name: sito1
    volumes:
       - Volume2:/usr/share/nginx/html
    ports:
      - "8081:80"
